// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgoU1cBUIaSLz7ytp9f9sxoNW1tBSih68',
    appId: '1:625199516844:web:5f47caafab35fcd62f6309',
    messagingSenderId: '625199516844',
    projectId: 'easynutrition-e052b',
    authDomain: 'easynutrition-e052b.firebaseapp.com',
    storageBucket: 'easynutrition-e052b.appspot.com',
    measurementId: 'G-FC39J9MD3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWVMQVj9xLjyv2MocRCOKtLnRGMKKyno',
    appId: '1:625199516844:android:51ce59d7bbcb22432f6309',
    messagingSenderId: '625199516844',
    projectId: 'easynutrition-e052b',
    storageBucket: 'easynutrition-e052b.appspot.com',
  );
}
